### PR TITLE
76 "barItems" stored in local storage not persisting on page reloads

### LINKED ISSUE #76: Tab Bar Items "barItems" stored data in localStorage does not persist on page reload
I am currently facing an issue where the data stored for Tab Bar Items "barItems" in localStorage does not persist on page reload. Instead, it gets replaced by the initial state defined as "barItems". I expect the previously stored data to be loaded from localStorage and used as the initial state.

**Code Sample:**
```javascript
const barItems = [{ id: 1, title: "Welcome", active: true }];

const [items, setItems] = useState([]);

useEffect(() => {
    const storedItems = window.localStorage.getItem("barItems");
    if (storedItems) {
      setItems(JSON.parse(storedItems));
    } else {
      setItems(barItems);
    }
}, []);
```

**Expected Behavior:**
1. On the initial load, the code should check if there is any data stored with the key "barItems" in localStorage.
2. If there is stored data, it should be retrieved and set as the initial state for the items state variable.
3. If no data is found in localStorage, the barItems array should be used as the initial state.

**Actual Behavior:**
The data stored in localStorage does not persist on page reload. Instead, the "barItems" array is used as the initial state, overwriting any previously stored data.

**Steps to Reproduce:**

1. Load the page "/".
2. Store some data in localStorage manually with the key "barItems" or add more tab bar with the first editor Navbar Icon .
3. Reload the page.
4. Observe that the stored data is replaced by the barItems array.

**Please let me know if I should work on this issue.**

### PR DESCRIPTION
**Pull request by NAJIB-B**
**This PR resolves #76 **

This PR fix the issue of "barItems" stored in local storage not persisting on page reloads.

### CODE REVIEW

File: src/app/page.js [hunk 1]
```diff
@@ -9,7 +9,14 @@ const barItems = [{ id: 1, title: "Welcome", active: true }];
 
 function Home() {
   const [items, setItems] = useState([]);
-
+  useEffect(() => {
+    if (items.length == 0) {
+      setItems(barItems);
+    } else {
+      console.log(items);
```
Comment (annonymousauthority) [inline src/app/page.js:16]: There's no need for console.log

File: src/app/page.js
Comment (annonymousauthority) [inline src/app/page.js:1]: You code doesn't have any changes that solves the problem

**Review by annonymousauthority — CHANGES_REQUESTED** [review]

**Review by annonymousauthority — APPROVED** [review]
LG
